name: "rust-clippy-check"
description: "Run clippy and annotate the diff with errors and warnings"
author: "actions-rs team, modified by @Kristof-Mattei"
branding:
  icon: play-circle
  color: orange

inputs:
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    required: false
  args:
    description: Arguments for the cargo command
    required: false
  use-cross:
    description: Use cross instead of cargo
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
